[project]
name = "scope-plugin-hello-world"
version = "0.1.0"
requires-python = ">=3.12"

[project.entry-points."scope"]
scope_plugin_hello_world = "scope_plugin_hello_world.plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
